#!/bin/bash
###################################################
## dprintm                                       ##
## print text files in emulated duplex using     ##
## enscript and dplx/duplex                      ##
## Call dprint with a mono-spaced font           ##
## Default printer and other settings are        ##
## specified in $HOME/.enscriptrc                ##
##                                               ##
## Calling sequence:                             ##
##  dprintm [enscript options] [dprint options]  ##
##          [<print-file>]                       ##
##                                               ##
## Should now pass all dprint and enscript       ##
## options to dprint and then to enscript        ##
##                                               ##
## Copyleft (c) 06 Oct 2014 Joseph J. Pollock    ##
##   JPmicrosystems - josephj at main.nc.us      ##
## Last modified 03/16/2018                      ##
##                                               ##
## This program is free software; you can        ##
## redistribute it and/or modify it under the    ##
## terms of the GNU General Public License as    ##
## published by the Free Software Foundation;    ##
## either version 2 of the License, or           ##
## (at your option) any later version.           ##
##                                               ##
## This program is distributed in the hope       ##
## that it will be useful, but WITHOUT ANY       ##
## WARRANTY; without even the implied warranty   ##
## of MERCHANTABILITY or FITNESS FOR A           ##
## PARTICULAR PURPOSE. See the GNU General       ##
## Public License for more details.              ##
##                                               ##
## You should have received a copy of the        ##
## GNU General Public License along with this    ##
## program; if not, write to                     ##
##    the Free Software Foundation, Inc.         ##
##    59 Temple Place - Suite 330                ##
##    Boston, MA  02111-1307, USA                ##
## See: http://www.gnu.org/copyleft/gpl.html     ##
###################################################

function mypath () {
  ## Get the real path of the calling script
  ##  From: https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within/
  my_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
}

mypath
script_path="${my_path}"  ## make sure we can find other scripts
"${script_path}"/dprint -font "Luxi-Mono" "$@"
